# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database_call.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61tabase_call.proto\"N\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\x04\x62ody\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_body\"\x1d\n\nLoginReply\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x32\x35\n\x0c\x44\x61tabaseCall\x12%\n\x05Login\x12\r.LoginRequest\x1a\x0b.LoginReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_call_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=23
  _LOGINREQUEST._serialized_end=101
  _LOGINREPLY._serialized_start=103
  _LOGINREPLY._serialized_end=132
  _DATABASECALL._serialized_start=134
  _DATABASECALL._serialized_end=187
# @@protoc_insertion_point(module_scope)
