# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eGoodbyeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cGoodbyeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\rInsultRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0bInsultReply\x12\x0e\n\x06insult\x18\x01 \x01(\t\"$\n\x0f\x44\x61tabaseRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\"!\n\rDatabaseReply\x12\x10\n\x08lastname\x18\x01 \x01(\t\"\x19\n\x0bInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\tInfoReply\x12\x0c\n\x04name\x18\x01 \x01(\t26\n\nHelloWorld\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x32\x39\n\x07Goodbye\x12.\n\nSayGoodbye\x12\x0f.GoodbyeRequest\x1a\r.GoodbyeReply\"\x00\x32\x38\n\x06Insult\x12.\n\x0cInsultPerson\x12\x0e.InsultRequest\x1a\x0c.InsultReply\"\x00\x32\x66\n\x0c\x44\x61tabaseCall\x12,\n\x06\x44\x42\x43\x61ll\x12\x10.DatabaseRequest\x1a\x0e.DatabaseReply\"\x00\x12(\n\nInfoFromID\x12\x0c.InfoRequest\x1a\n.InfoReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=14
  _HELLOREQUEST._serialized_end=42
  _HELLOREPLY._serialized_start=44
  _HELLOREPLY._serialized_end=73
  _GOODBYEREQUEST._serialized_start=75
  _GOODBYEREQUEST._serialized_end=105
  _GOODBYEREPLY._serialized_start=107
  _GOODBYEREPLY._serialized_end=138
  _INSULTREQUEST._serialized_start=140
  _INSULTREQUEST._serialized_end=169
  _INSULTREPLY._serialized_start=171
  _INSULTREPLY._serialized_end=200
  _DATABASEREQUEST._serialized_start=202
  _DATABASEREQUEST._serialized_end=238
  _DATABASEREPLY._serialized_start=240
  _DATABASEREPLY._serialized_end=273
  _INFOREQUEST._serialized_start=275
  _INFOREQUEST._serialized_end=300
  _INFOREPLY._serialized_start=302
  _INFOREPLY._serialized_end=327
  _HELLOWORLD._serialized_start=329
  _HELLOWORLD._serialized_end=383
  _GOODBYE._serialized_start=385
  _GOODBYE._serialized_end=442
  _INSULT._serialized_start=444
  _INSULT._serialized_end=500
  _DATABASECALL._serialized_start=502
  _DATABASECALL._serialized_end=604
# @@protoc_insertion_point(module_scope)
