# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import demo_pb2 as demo__pb2


class HelloWorldStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/HelloWorld/SayHello',
                request_serializer=demo__pb2.HelloRequest.SerializeToString,
                response_deserializer=demo__pb2.HelloReply.FromString,
                )


class HelloWorldServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloWorldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=demo__pb2.HelloRequest.FromString,
                    response_serializer=demo__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HelloWorld', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloWorld(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HelloWorld/SayHello',
            demo__pb2.HelloRequest.SerializeToString,
            demo__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GoodbyeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayGoodbye = channel.unary_unary(
                '/Goodbye/SayGoodbye',
                request_serializer=demo__pb2.GoodbyeRequest.SerializeToString,
                response_deserializer=demo__pb2.GoodbyeReply.FromString,
                )


class GoodbyeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayGoodbye(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoodbyeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayGoodbye': grpc.unary_unary_rpc_method_handler(
                    servicer.SayGoodbye,
                    request_deserializer=demo__pb2.GoodbyeRequest.FromString,
                    response_serializer=demo__pb2.GoodbyeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Goodbye', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Goodbye(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayGoodbye(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Goodbye/SayGoodbye',
            demo__pb2.GoodbyeRequest.SerializeToString,
            demo__pb2.GoodbyeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InsultStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsultPerson = channel.unary_unary(
                '/Insult/InsultPerson',
                request_serializer=demo__pb2.InsultRequest.SerializeToString,
                response_deserializer=demo__pb2.InsultReply.FromString,
                )


class InsultServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsultPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsultPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.InsultPerson,
                    request_deserializer=demo__pb2.InsultRequest.FromString,
                    response_serializer=demo__pb2.InsultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Insult', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Insult(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsultPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Insult/InsultPerson',
            demo__pb2.InsultRequest.SerializeToString,
            demo__pb2.InsultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DatabaseCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DBCall = channel.unary_unary(
                '/DatabaseCall/DBCall',
                request_serializer=demo__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=demo__pb2.DatabaseReply.FromString,
                )
        self.InfoFromID = channel.unary_unary(
                '/DatabaseCall/InfoFromID',
                request_serializer=demo__pb2.InfoRequest.SerializeToString,
                response_deserializer=demo__pb2.InfoReply.FromString,
                )


class DatabaseCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DBCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InfoFromID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DBCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DBCall,
                    request_deserializer=demo__pb2.DatabaseRequest.FromString,
                    response_serializer=demo__pb2.DatabaseReply.SerializeToString,
            ),
            'InfoFromID': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoFromID,
                    request_deserializer=demo__pb2.InfoRequest.FromString,
                    response_serializer=demo__pb2.InfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DBCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseCall/DBCall',
            demo__pb2.DatabaseRequest.SerializeToString,
            demo__pb2.DatabaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InfoFromID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseCall/InfoFromID',
            demo__pb2.InfoRequest.SerializeToString,
            demo__pb2.InfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
