# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_files import demo_pb2 as demo__pb2


class DatabaseCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DBCall = channel.unary_unary(
                '/DatabaseCall/DBCall',
                request_serializer=demo__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=demo__pb2.DatabaseReply.FromString,
                )
        self.InfoFromID = channel.unary_unary(
                '/DatabaseCall/InfoFromID',
                request_serializer=demo__pb2.InfoRequest.SerializeToString,
                response_deserializer=demo__pb2.InfoReply.FromString,
                )


class DatabaseCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DBCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InfoFromID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DBCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DBCall,
                    request_deserializer=demo__pb2.DatabaseRequest.FromString,
                    response_serializer=demo__pb2.DatabaseReply.SerializeToString,
            ),
            'InfoFromID': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoFromID,
                    request_deserializer=demo__pb2.InfoRequest.FromString,
                    response_serializer=demo__pb2.InfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DBCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseCall/DBCall',
            demo__pb2.DatabaseRequest.SerializeToString,
            demo__pb2.DatabaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InfoFromID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseCall/InfoFromID',
            demo__pb2.InfoRequest.SerializeToString,
            demo__pb2.InfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
