# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python.proto_files.class_files.class_pb2 as class__pb2


class ClassCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddClass = channel.unary_unary(
                '/ClassCall/AddClass',
                request_serializer=class__pb2.AddClassRequest.SerializeToString,
                response_deserializer=class__pb2.AddClassReply.FromString,
                )
        self.RemoveClass = channel.unary_unary(
                '/ClassCall/RemoveClass',
                request_serializer=class__pb2.RemoveClassRequest.SerializeToString,
                response_deserializer=class__pb2.RemoveClassReply.FromString,
                )
        self.AddUserToClass = channel.unary_unary(
                '/ClassCall/AddUserToClass',
                request_serializer=class__pb2.AddUserToClassRequest.SerializeToString,
                response_deserializer=class__pb2.AddUserToClassReply.FromString,
                )
        self.RemoveUserFromClass = channel.unary_unary(
                '/ClassCall/RemoveUserFromClass',
                request_serializer=class__pb2.RemoveUserFromClassRequest.SerializeToString,
                response_deserializer=class__pb2.RemoveUserFromClassReply.FromString,
                )


class ClassCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddClass': grpc.unary_unary_rpc_method_handler(
                    servicer.AddClass,
                    request_deserializer=class__pb2.AddClassRequest.FromString,
                    response_serializer=class__pb2.AddClassReply.SerializeToString,
            ),
            'RemoveClass': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveClass,
                    request_deserializer=class__pb2.RemoveClassRequest.FromString,
                    response_serializer=class__pb2.RemoveClassReply.SerializeToString,
            ),
            'AddUserToClass': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToClass,
                    request_deserializer=class__pb2.AddUserToClassRequest.FromString,
                    response_serializer=class__pb2.AddUserToClassReply.SerializeToString,
            ),
            'RemoveUserFromClass': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromClass,
                    request_deserializer=class__pb2.RemoveUserFromClassRequest.FromString,
                    response_serializer=class__pb2.RemoveUserFromClassReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassCall/AddClass',
            class__pb2.AddClassRequest.SerializeToString,
            class__pb2.AddClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassCall/RemoveClass',
            class__pb2.RemoveClassRequest.SerializeToString,
            class__pb2.RemoveClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserToClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassCall/AddUserToClass',
            class__pb2.AddUserToClassRequest.SerializeToString,
            class__pb2.AddUserToClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUserFromClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClassCall/RemoveUserFromClass',
            class__pb2.RemoveUserFromClassRequest.SerializeToString,
            class__pb2.RemoveUserFromClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
