# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lass.proto\"^\n\x0f\x41\x64\x64\x43lassRequest\x12\x18\n\x10teacher_username\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x0c\n\x04hour\x18\x03 \x01(\x05\x12\x0f\n\x07room_id\x18\x04 \x01(\x05\"&\n\x12RemoveClassRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\";\n\x15\x41\x64\x64UserToClassRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"@\n\x1aRemoveUserFromClassRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"/\n\x1bGetAllUsersFromClassRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\"0\n\x1cGetAllChairsFromClassRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\"\\\n\x05Reply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x42\n\n\x08_messageB\x08\n\x06_error2\xd5\x02\n\tClassCall\x12&\n\x08\x41\x64\x64\x43lass\x12\x10.AddClassRequest\x1a\x06.Reply\"\x00\x12,\n\x0bRemoveClass\x12\x13.RemoveClassRequest\x1a\x06.Reply\"\x00\x12\x32\n\x0e\x41\x64\x64UserToClass\x12\x16.AddUserToClassRequest\x1a\x06.Reply\"\x00\x12<\n\x13RemoveUserFromClass\x12\x1b.RemoveUserFromClassRequest\x1a\x06.Reply\"\x00\x12>\n\x14GetAllUsersFromClass\x12\x1c.GetAllUsersFromClassRequest\x1a\x06.Reply\"\x00\x12@\n\x15GetAllChairsFromClass\x12\x1d.GetAllChairsFromClassRequest\x1a\x06.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'class_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDCLASSREQUEST._serialized_start=15
  _ADDCLASSREQUEST._serialized_end=109
  _REMOVECLASSREQUEST._serialized_start=111
  _REMOVECLASSREQUEST._serialized_end=149
  _ADDUSERTOCLASSREQUEST._serialized_start=151
  _ADDUSERTOCLASSREQUEST._serialized_end=210
  _REMOVEUSERFROMCLASSREQUEST._serialized_start=212
  _REMOVEUSERFROMCLASSREQUEST._serialized_end=276
  _GETALLUSERSFROMCLASSREQUEST._serialized_start=278
  _GETALLUSERSFROMCLASSREQUEST._serialized_end=325
  _GETALLCHAIRSFROMCLASSREQUEST._serialized_start=327
  _GETALLCHAIRSFROMCLASSREQUEST._serialized_end=375
  _REPLY._serialized_start=377
  _REPLY._serialized_end=469
  _CLASSCALL._serialized_start=472
  _CLASSCALL._serialized_end=813
# @@protoc_insertion_point(module_scope)
