# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seating.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rseating.proto\"E\n\x1c\x41\x64\x64SeatingArrangementRequest\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61rrangement\x18\x02 \x01(\t\"q\n\x1a\x41\x64\x64SeatingArrangementReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x42\n\n\x08_messageB\x08\n\x06_error2d\n\x0bSeatingCall\x12U\n\x15\x41\x64\x64SeatingArrangement\x12\x1d.AddSeatingArrangementRequest\x1a\x1b.AddSeatingArrangementReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seating_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDSEATINGARRANGEMENTREQUEST._serialized_start=17
  _ADDSEATINGARRANGEMENTREQUEST._serialized_end=86
  _ADDSEATINGARRANGEMENTREPLY._serialized_start=88
  _ADDSEATINGARRANGEMENTREPLY._serialized_end=201
  _SEATINGCALL._serialized_start=203
  _SEATINGCALL._serialized_end=303
# @@protoc_insertion_point(module_scope)
