# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python.proto_files.seating.seating_pb2 as seating__pb2


class SeatingCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSeatingArrangement = channel.unary_unary(
                '/SeatingCall/AddSeatingArrangement',
                request_serializer=seating__pb2.AddSeatingArrangementRequest.SerializeToString,
                response_deserializer=seating__pb2.AddSeatingArrangementReply.FromString,
                )


class SeatingCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSeatingArrangement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeatingCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSeatingArrangement': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSeatingArrangement,
                    request_deserializer=seating__pb2.AddSeatingArrangementRequest.FromString,
                    response_serializer=seating__pb2.AddSeatingArrangementReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SeatingCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SeatingCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSeatingArrangement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SeatingCall/AddSeatingArrangement',
            seating__pb2.AddSeatingArrangementRequest.SerializeToString,
            seating__pb2.AddSeatingArrangementReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
