# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_files.database import database_call_pb2 as database__call__pb2


class DatabaseCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckLogin = channel.unary_unary(
                '/DatabaseCall/CheckLogin',
                request_serializer=database__call__pb2.LoginRequest.SerializeToString,
                response_deserializer=database__call__pb2.LoginReply.FromString,
                )


class DatabaseCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLogin,
                    request_deserializer=database__call__pb2.LoginRequest.FromString,
                    response_serializer=database__call__pb2.LoginReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseCall/CheckLogin',
            database__call__pb2.LoginRequest.SerializeToString,
            database__call__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
