# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import python.proto_files.admin.admin_pb2 as admin__pb2


class AdminCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/AdminCall/AddUser',
                request_serializer=admin__pb2.AddUserRequest.SerializeToString,
                response_deserializer=admin__pb2.AddUserReply.FromString,
                )
        self.RemoveUser = channel.unary_unary(
                '/AdminCall/RemoveUser',
                request_serializer=admin__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=admin__pb2.RemoveUserReply.FromString,
                )
        self.AddClass = channel.unary_unary(
                '/AdminCall/AddClass',
                request_serializer=admin__pb2.AddClassRequest.SerializeToString,
                response_deserializer=admin__pb2.AddClassReply.FromString,
                )
        self.RemoveClass = channel.unary_unary(
                '/AdminCall/RemoveClass',
                request_serializer=admin__pb2.RemoveClassRequest.SerializeToString,
                response_deserializer=admin__pb2.RemoveClassReply.FromString,
                )


class AdminCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=admin__pb2.AddUserRequest.FromString,
                    response_serializer=admin__pb2.AddUserReply.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=admin__pb2.RemoveUserRequest.FromString,
                    response_serializer=admin__pb2.RemoveUserReply.SerializeToString,
            ),
            'AddClass': grpc.unary_unary_rpc_method_handler(
                    servicer.AddClass,
                    request_deserializer=admin__pb2.AddClassRequest.FromString,
                    response_serializer=admin__pb2.AddClassReply.SerializeToString,
            ),
            'RemoveClass': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveClass,
                    request_deserializer=admin__pb2.RemoveClassRequest.FromString,
                    response_serializer=admin__pb2.RemoveClassReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AdminCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminCall/AddUser',
            admin__pb2.AddUserRequest.SerializeToString,
            admin__pb2.AddUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminCall/RemoveUser',
            admin__pb2.RemoveUserRequest.SerializeToString,
            admin__pb2.RemoveUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminCall/AddClass',
            admin__pb2.AddClassRequest.SerializeToString,
            admin__pb2.AddClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminCall/RemoveClass',
            admin__pb2.RemoveClassRequest.SerializeToString,
            admin__pb2.RemoveClassReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
