# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\"|\n\nAddRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x15\n\ruser_password\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0f\n\x07role_id\x18\x06 \x01(\x05\"_\n\x08\x41\x64\x64Reply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x42\n\n\x08_messageB\x08\n\x06_error\" \n\rRemoveRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"b\n\x0bRemoveReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x42\n\n\x08_messageB\x08\n\x06_error2^\n\tAdminCall\x12#\n\x07\x41\x64\x64User\x12\x0b.AddRequest\x1a\t.AddReply\"\x00\x12,\n\nRemoveUser\x12\x0e.RemoveRequest\x1a\x0c.RemoveReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDREQUEST._serialized_start=15
  _ADDREQUEST._serialized_end=139
  _ADDREPLY._serialized_start=141
  _ADDREPLY._serialized_end=236
  _REMOVEREQUEST._serialized_start=238
  _REMOVEREQUEST._serialized_end=270
  _REMOVEREPLY._serialized_start=272
  _REMOVEREPLY._serialized_end=370
  _ADMINCALL._serialized_start=372
  _ADMINCALL._serialized_end=466
# @@protoc_insertion_point(module_scope)
